### ISSUE TITLE
best way to create a dataset computed from other datasets?

### ISSUE THREAD

**Issue by etiennesky** [SantanderMetGroup/loadeR#31]
Hi,
I am working with the firedangeR package and I need to compute hurs (relative humidity) from tas and tdpa, obtained from the era-interim dataset, with the

This is the way I am doing it using the  tdps2hurs function, but I suspect there is a better way...

tas=loadGridData(dataset = var_ncml_file,var=var_name,lonLim=lonLim,latLim=latLim,years=years)
hurs=tas
hurs$Data=tdps2hurs(tas$Data, tdps$Data)
hurs$Variable$varName="hurs"
attributes(hurs$Variable)$longname="hurs"
attributes(hurs$Variable)$description="2-meter relative humidity"
attributes(hurs$Variable)$units="%"

Also is this the right place to submit a question like this? 

Thanks!

**Comment by jbedia** [comment]
Hi @etiennesky , thanks for your question. You can either post it here or in the fireDanger list (maybe here is more relevant). In any case, the best way to obtain derived variables is via dictionary, so the calculation of derived variables is done behind the scenes. There are examples of derived variables in the [loadeR.ECOMS](https://github.com/SantanderMetGroup/loadeR.ECOMS) package, in order to transparently provide users derived variables like hurss. See for instance the [dictionary](https://github.com/SantanderMetGroup/loadeR.ECOMS/blob/devel/inst/dictionaries/CFSv2_seasonal.dic) of the CFSv2 hindcast. I hope this helps

**Comment by etiennesky** [comment]
Hi @jbedia thanks for your answer. 

However, it is not clear to me how to create derived variables from datasets obtained from local files via loadGridData and not via loadeR.ECOMS . 

I guess I would need to create a dictionnary for the data source as well as create a function similar to deriveSurfaceRelativeHumidity.CFS.R ?

**Comment by jbedia** [comment]
Yes, that would be the approach I'd follow, so you can directly load relative humidity without worrying about the conversion every time you need it
