### ISSUE TITLE
Problem with loadStationData

### ISSUE THREAD

**Issue by rodaguayo** [SantanderMetGroup/loadeR#41]
I can not use the loadStationData function with these attachments, I have tried almost all the combinations reading the tutorial and trying to simulate the sample files.

"Error in `[.data.frame`(read.csv(unzcond(dataset, zipFileContents[fileInd]),  : 
  undefined columns selected"

[variables.txt](https://github.com/SantanderMetGroup/loadeR/files/2150733/variables.txt)
[stations.txt](https://github.com/SantanderMetGroup/loadeR/files/2150734/stations.txt)
[precip.txt](https://github.com/SantanderMetGroup/loadeR/files/2150735/precip.txt)

Thank you very much for your time
PD: dataInventory works fine for the files

**Comment by miturbide** [comment]
Hi @rodaguayo,
Thanks for reporting. A little bug was accidentally recovered from a previous version of the function. Please, try again using the devel version of the package:
devtools::install_github(c("SantanderMetGroup/loadeR@devel")).

**Comment by rodaguayo** [comment]
Thanks!

**Comment by rodaguayo** [comment]
Hi @miturbide , thanks for your time!

**Comment by DanielaOsses** [comment]
hi @miturbide I have the same issue and i've already installed the 1.4.4 version (devtools::install_github("SantanderMetGroup/loadeR@v1.4.4"), what could it be?

Thanks

[variables.txt](https://github.com/SantanderMetGroup/loadeR/files/6619752/variables.txt)
[stations.txt](https://github.com/SantanderMetGroup/loadeR/files/6619753/stations.txt)
[tmin.txt](https://github.com/SantanderMetGroup/loadeR/files/6619754/tmin.txt)

**Comment by anacv** [comment]
Hi, 
@DanielaOsses problem was due to different stations in stations.txt and tmin.txt (larger set of stations in stations.txt than in tmin.txt) and it was solved by using the argument 'stationID' indicating the stations code with data in tmin.txt. Since it is common to have data for different variables at different stations (e.g. tas vs precip), would it be possible for loadStationData to do this automatically, i.e. to filter and retrieve the common stationIDs in both files, @miturbide , @jbedia?
Thanks!

**Comment by jbedia** [comment]
Hi, if all stations belong to the same dataset, all stations listed in stations.txt must be included for consistency. Otherwise, a different dataset should be created.
In my view, the most straightforward solution in this particular case is filling in with NaN the missing data series.
cheers

**Comment by anacv** [comment]
OK, understood. Thanks!
