### ISSUE TITLE
Error in loading station data

### ISSUE THREAD

**Issue by idriswada007** [SantanderMetGroup/loadeR#90]
I am trying to load station data for bias correction and I got the error below.
code used:
obsprecip <- loadStationData(dataset = dir.obs, 
                            var="precip", 
                            stationID = c("kn01", "jg02", "ba03", "kt04"), 
                            season = 5:10, 
                            years = 1991:2015)

and the error:
[2022-12-14 22:00:02] Loading data ...
[2022-12-14 22:00:02] Retrieving metadata ...
Error in if (class(out$Data) == "numeric") datadimnames <- "time" : 
  the condition has length > 1

I have my text files in the directory and in the correct format. please what could possibly be the cause of this error?
thank you

find attached the text files.

[precip.txt](https://github.com/SantanderMetGroup/loadeR/files/10231704/precip.txt)
[stations.txt](https://github.com/SantanderMetGroup/loadeR/files/10231705/stations.txt)
[tmax.txt](https://github.com/SantanderMetGroup/loadeR/files/10231706/tmax.txt)
[tmin.txt](https://github.com/SantanderMetGroup/loadeR/files/10231708/tmin.txt)
[variables.txt](https://github.com/SantanderMetGroup/loadeR/files/10231713/variables.txt)

**Comment by idriswada007** [comment]
@miturbide, @anacv, @jbedia 
please do you have an idea about this error? 
thank you.

**Comment by idriswada007** [comment]
i am using loadeR version 1.7.2

**Comment by Richard-Chandler** [comment]
The issue is the line 

if (class(out$Data) == "numeric")

which now causes a problem because class(out$Data) gives a vector c("matrix", "array"). Perhaps a consequence of a recent R update? To avoid it, change the line to 

if (isTRUE(class(out$Data) == "numeric"))

If you don't have edit access to the repo, just create a local copy of the loadStationData function and edit it. 

Hope this helps, 
Richard

**Comment by miturbide** [comment]
Hi @idriswada007 and thanks @Richard-Chandler.
As @Richard-Chandler pointed out, this bug is due to an R update, where the class of an array or a matrix is defined with two characters ('c("array", "array")') instead of one.

This has been corrected in the devel branch by replacing the conflicting line with 'if ("numeric" %in% class(out$Data))'. You can use this branch until a new version of loadeR is released. To install the branch:

> library(devtools)
> install_github("SantanderMetGroup/loadeR@devel")

**Comment by idriswada007** [comment]
Thanks very much, installing the devel update solved the issue.
